[package]
name = "bounce_shield"
version = "1.0.0"
edition = "2024"

[dependencies]
# rand = "0.8.5"
macroquad = "0.4.13"
bevy = "0.15.0"
bevy_tweening = "0.12.0"
bevy_math = "0.15.0"
bevy_rand = "0.8.0"

[lib]
name = "bounce_shield"
path = "lib/lib.rs"