name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  #windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly-2021-09-01  # Specify a specific version for consistency

    - name: Cache Rust dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Add Targets
      run: |
        rustup target add x86_64-apple-darwin x86_64-unknown-linux-gnu
#       x86_64-pc-windows-msvc

    - name: Build And Release
      run: |
        # Build the project for the specified target platform (based on matrix configuration)
        cargo build --release --target ${{ matrix.os }}

    - name: Upload Release Assets
      uses: actions/upload-artifact@v2
      with:
        name: bounceshield
        path: |
          target/x86_64-apple-darwin/release/bounceshield
          target/x86_64-unknown-linux-gnu/release/bounceshield
#         target/x86_64-pc-windows-msvc/release/bounceshield.exe