name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly

    - name: Add Targets
      run: |
        rustup target add x86_64-apple-darwin
        rustup target add x86_64-pc-windows-msvc
        rustup target add x86_64-unknown-linux-gnu

    - name: Build And Release
      run: |
        cargo build --release --target ${{ matrix.os }}  # Use the correct matrix target

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/x86_64-apple-darwin/release/bounceshield
          target/x86_64-pc-windows-msvc/release/bounceshield.exe
          target/x86_64-unknown-linux-gnu/release/bounceshield
