name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust (nightly)
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly

    - name: Install Target for cross-compiling (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: rustup target add x86_64-unknown-linux-gnu

    - name: Cache Rust dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install Cross-Compilation Tools (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-multilib g++-multilib

    - name: Install Cross-Compilation Tools (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install FiloSottile/musl-cross/musl-cross

    - name: Clean previous build artifacts
      run: cargo clean

    - name: Build for Linux (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        export CC=musl-gcc
        export CXX=musl-g++
        cargo build --release --target x86_64-unknown-linux-gnu --verbose
        ls -la target/x86_64-unknown-linux-gnu/release/
    
    - name: Build for Linux (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
          cargo build --release --target x86_64-unknown-linux-gnu --bin bounceshield --verbose
          ls -la target/x86_64-unknown-linux-gnu/release/

    - name: Package Binary (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        mkdir -p release/mac
        cp target/x86_64-unknown-linux-gnu/release/bounceshield release/mac/bounceshield
        tar -czf release/mac/bounceshield-mac.tar.gz -C release/mac bounceshield

    - name: Package Binary (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        mkdir -p release/linux
        cp target/x86_64-unknown-linux-gnu/release/bounceshield release/linux/bounceshield
        tar -czf release/linux/bounceshield-linux.tar.gz -C release/linux bounceshield

    - name: Upload macOS Binary
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: bounceshield-mac
        path: release/mac/bounceshield-mac.tar.gz

    - name: Upload Linux Binary
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: bounceshield-linux
        path: release/linux/bounceshield-linux.tar.gz
